# Generated by Django 3.1.7 on 2021-11-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=255)),
                ('edad', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=20)),
            ],
        ),
    ]
